### ISSUE TITLE
1 million points

### ISSUE THREAD

**Issue by oniregoc** [cpesch/RouteConverter#55]
In fact there is no bug unless your very useful application can't add elevation to the 1002008  points I need...of course I understand it's very unusual ! So in fact it's more a request : can you add that abilities ? Thanks if so it will save me a lot of time !

**Comment by cpesch** [comment]
The source is there. Why don't you use it?

Otherwise I'll cost me a lot of time to save you a lot of time.

**Comment by oniregoc** [comment]
maybe because I am not devloper, don't know anything to java and don't know
where the problem is ?

Thanks anyway.


*.Bali.Angelo.Cogérino.*
*P  h  o  t  o  g  r  a  p  h  e  r*

*http://www.cogerino.com <http://www.cogerino.com>*
*Tel : +33 680714013*

------------------------------

*The informations contained in t**his message **and any attachments are
confidential and intended solely for the addressees.  If the reader of this
message is not the intended recipient, you are hereby notified that any
unauthorized use, copying or dissemination is strictly prohibited. E-mails
are susceptible to alteration. Neither Bali Angelo Cogerino nor any of its
subsidiaries or affiliates shall be liable for the message if altered,
changed or falsified. If you received this communication in error, please
delete it and **notify the** sender.*

------------------------------




Le lun. 8 juil. 2019 à 11:28, Christian Pesch <notifications@github.com> a
écrit :

**Comment by cpesch** [comment]
Dear Angelo,

 

although I haven't fully understood what you want to achieve,

it seems to me the problem isn't big.

 

But in the end someone has to do the implementation work.

If you can't do it, you have to find someone who can ;-)
 

Best regards

--
Christian

 
 

Gesendet: Montag, 08. Juli 2019 um 12:01 Uhr
Von: "oniregoc" <notifications@github.com>
An: cpesch/RouteConverter <RouteConverter@noreply.github.com>
Cc: "Christian Pesch" <Christian_Pesch@gmx.de>, "State change" <state_change@noreply.github.com>
Betreff: Re: [cpesch/RouteConverter] 1 million points (#55)

maybe because I am not devloper, don't know anything to java and don't know
where the problem is ?

Thanks anyway.


*.Bali.Angelo.Cogérino.*
*P h o t o g r a p h e r*

*http://www.cogerino.com <http://www.cogerino.com>*
*Tel : +33 680714013*

------------------------------

*The informations contained in t**his message **and any attachments are
confidential and intended solely for the addressees. If the reader of this
message is not the intended recipient, you are hereby notified that any
unauthorized use, copying or dissemination is strictly prohibited. E-mails
are susceptible to alteration. Neither Bali Angelo Cogerino nor any of its
subsidiaries or affiliates shall be liable for the message if altered,
changed or falsified. If you received this communication in error, please
delete it and **notify the** sender.*

------------------------------




Le lun. 8 juil. 2019 à 11:28, Christian Pesch <notifications@github.com> a
écrit :
