### ISSUE TITLE
Windows EXE does not start with Java 15

### ISSUE THREAD

**Issue by McPringle** [cpesch/RouteConverter#61]
Hi, on my System (Windows 10) I have Java 15 installed (and in the PATH). Using the Windows EXE, it complains about missing Java 8:

![image](https://user-images.githubusercontent.com/1254039/103417968-36651c00-4b8d-11eb-8190-c17ac730617d.png)

This happens with the stable and with the prerelease version. I downloaded the JAR file, and it works perfectly with Java 15. So I think the problem is in the part of the code for the EXE file.

Java 8 is *end of public updates* and the EXE of RouteConverter should support (recognize) newer Java versions.

**Comment by cpesch** [comment]
I'm using launch4j via the launch4j-maven-plugin (see https://github.com/cpesch/RouteConverter/blob/master/RouteConverterWindowsOpenSource/pom.xml).

And I've configured <minVersion>8</minVersion> because that is the last JRE which is available as 32-bits. And my computer is old and only allows for a 32-bit Windows.

@McPringle could you try if bumping up the JRE minVersion to 11 makes launch4j detect your OpenJDK 15?

**Comment by cpesch** [comment]
I strongly assume, that the behaviour that you see, is connected to your AdoptOpenJDK installation.

I've ticked the boxes that make the AdoptOpenJDK available in JAVA_HOME and the Oracle registry keys:

![Bildschirmfoto 2021-01-01 um 13 51 29](https://user-images.githubusercontent.com/40717/103438933-cb711f00-4c38-11eb-8e19-e015826fa87a.png)

Thus the launch4j .exe stub can see the AdoptOpenJDK:

![Bildschirmfoto 2021-01-01 um 13 46 17](https://user-images.githubusercontent.com/40717/103438957-ee033800-4c38-11eb-9a65-7cd85a349af7.png)
