### ISSUE TITLE
Only OSM available?

### ISSUE THREAD

**Issue by Tiemichael** [cpesch/RouteConverter#81]
Hi,
I have been using the great program for many years, mainly to plan my holidays.

After downloading the most recent version (and Java) on a new PC, I am only offered OpenStreetMap.
No other Online or Offline Maps show.
The same version is showing the usual map-options, on my old PC where RC was/is running for a long time.
Any idea what I could be doing wrong?
Thanks!

PS: I am unable to register at the Userforum, I says Captcha cannot be conformed, but there is NO Captcha displayed

**Comment by cpesch** [comment]
Hi @Tiemichael,

I have big problems with the availability of the existing server and the setup of its successor.

That's why your RouteConverter is not able to download meta data about maps, routing and elevation information. So it's falling back to the default: OpenStreetMap.

You could copy the $HOME/.routeconverter from another machine to solve the problem.

**Comment by Tiemichael** [comment]
Thanks for your reply!
Problem Fixed!

**Comment by Tiemichael** [comment]
Thanks for your reply!
Problem Fixed!
